apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  values:
    cluster:
      name: cluster-newyork
      id: 2
    k8sServiceHost: cp.newyork.internal
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.201.0.0/16
    clustermesh:
      apiserver:
        tls:
          server:
            extraDnsNames:
              - "*.clustermesh.internal"
              - cp.newyork.clustermesh.internal
