extends: default

rules:
  line-length:
    max: 180
    level: warning

  # Allow Jinja2 template syntax {{ ... }} which often has spaces inside braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1

  # Allow some flexibility in comments
  comments:
    min-spaces-from-content: 1

  document-start: disable

ignore: |
  flux/clusters/**/flux-system/
