apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  values:
    cluster:
      name: cluster-paris
      id: 1
    k8sServiceHost: cp.paris.internal
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.200.0.0/16
    clustermesh:
      apiserver:
        tls:
          server:
            extraDnsNames:
              - "*.clustermesh.internal"
              - cp.paris.clustermesh.internal
