apiVersion: v1
kind: Service
metadata:
  name: cilium-gateway-cilium-gateway
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
    - name: port-80
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: port-443
      port: 443
      targetPort: 443
      nodePort: 30443
